export function getHotelinfo() {
    return hotelInfo
}

let hotelInfo = [
    {hotelname: "Dolly sun Hotel", 
     destination: "Spanien", 
     location: "Barcelona", 
     seadistance: "500 meter från stranden", 
     hoteltransfer: "Transfer går att boka", 
     shortdesc: " Hotellet är skapat i klassisk medelhavsstil och har fritt wi-fi",
     talldesc: "Dolly Sun Hotel erbjuder dig att koppla av i en våra 2 bubbelpooler. Detta hotell rustat i medelhavsstil har gratis wi-fi, conciergetjänster och för föräldrar erbjuder vi även barnpassning mot avgift.  Detta hotell har all inclusive-priser och inkluderar mat och dryck på deras restauranger. När du vill äta något på hotellet, kan du välja mellan deras två restauranger och deras två kafé. Hotellet är tillmötesgående när det gäller allergier och vi ser till att alla kan få något att äta. Frukostbuffé serveras dagligen från 08:00 till 10:00. ",
     image:"https://images.pexels.com/photos/1268871/pexels-photo-1268871.jpeg?auto=compress&cs=tinysrgb&w=800",
     features: "1 rumslägenhet • 2 rumslägenhet • Familjesvit",
     payment: "Betala nu • Dela upp betalningen",
     food: "Lactosfri • Vegetarisk • Vegansk",
     price: "Från 16.060:-",
     recomends: "Familjer",
     review: 3.0,
     facilities:"✓ Fitness center  ✓Pool  ✓ WIfI  ✓ Barnpassning"},
    

     {hotelname: "Geluy Hotel", 
     destination: "spanien", 
     location: "Ibiza", 
     seadistance: "1000 meter från stranden", 
     hoteltransfer: "Transfer går att boka", 
     shortdesc: "Tillgång till en större utomhuspool. Detta hotell har gratis wi-fi, en tv i allmänt utrymme",
     talldesc: "Du kan stilla din aptit i våran loungebar som serverar både lunch och middag. Mat för alla, prata med personalen så fixar dom det. Skulle du hellre vilja spendera tid och mysa på rummet har du dessutom tillgång till rumsservice. Frukost serveras mot en avgift varje dag mellan 08:00 och 11:00. Restauranggäster har tillgång till bland annat en dator, bagageförvaring och värdeförvaringsskåp i receptionen på hotellet.",
     image:"https://images.pexels.com/photos/9696248/pexels-photo-9696248.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
     features: "1 rumslägenhet • 2 rumslägenhet • Familjerum",
     payment: "Betala nu • Dela upp betalningen",
     food: "Lactosfri • Vegetarisk ",
     price: "från 8.400:-",
     recomends: "Familjer",
     review: 2.0, 
     facilities:"✓ Loungebar  ✓Pool  ✓ WIfI" },

     {hotelname: "Luxury Abby Spa Hotel", 
     destination: "spanien",
     location: "Mallorca", 
     seadistance: "0 meter från stranden", 
     hoteltransfer: "Transfer ingår i bokningen", 
     shortdesc: "Känn dig som en superstar med den förstklassiga servicen på Luxary Abby Spa Hotel",
     talldesc:"Detta stilfullt inredda hotell erbjuder en perfekt balans mellan elegans och komfort. Hotellet är som en lugn och välkomnande oas och är välkomnande för familjemedlemmar i alla åldrar. Luxary Abby  ligger i Cala Ratjada. Den stilrena och klassiskt inredda receptionen och terrasserna omges av en vacker trädgård som sköts av hotellets många vaktmästare. En filosofi vi har är att en vacker trädgård är den bästa medicinen för själen. Den vänliga personalen ser till att du blir väl omhändertagen",
     image: "https://images.pexels.com/photos/9860910/pexels-photo-9860910.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
     features: "1 rumslägenhet • 2 rumslägenhet • silversvit • guldsvit",
     payment: "Betala nu • Dela upp betalningen",
     food: "Lactosfri • Vegetarisk • Rawfood",
     price: "Från 23.980",
     recomends: "Familjer",
     review: 5.0,    
     facilities:"✓Terass  ✓Pool  ✓ WIfI  ✓Gym  ✓Tennisbanna" },

     {hotelname: "Sea Star Hotel", 
     destination: "Spanien",
     location: "Menorca", 
     seadistance: "500 meter från stranden", 
     hoteltransfer: "Transfer ingår i bokning", 
     shortdesc: "Sea Star ligger på stranden Cala Estancia vid den vackra Palmabukten, och välkomnar endast vuxna gäster. ",
     talldesc: "Alla rum har luftkonditionering, stora rymliga badrum, privat balkong, platt-tv och gratis WiFi. Sea Star har en stor solterrass och en säsongsöppen utomhuspool. Boendet har underbar utsikt över Palmabukten och Medelhavet. Restaurangen serverar en buffé med medelhavsmat och internationella rätter till frukost, lunch och middag. Hotellet har även en poolbar på poolområdet och en utsökt kaffebar.",
     image:"https://cf.bstatic.com/xdata/images/hotel/max1280x900/322658536.jpg?k=3fffe63a365fd0ccdc59210188e55188cdb7448b9ec1ddb71b0843172138ec07&o=&hp=1",
     features: "1 rumslägenhet • 2 rumslägenhet • Familjesvit",
     payment: "Betala nu • Dela upp betalningen",
     food: "Lactosfri • Vegetarisk • Vegansk",
     price: "Från 21.980:-",
     recomends: "För par",
     review: 4.0,
     facilities:"✓Luftkondtionering ✓Pool  ✓ WIfI  ✓Solterass  ✓Kaffebar" },

     {hotelname: "Barracuda Beach Hotel", 
     destination: "Spanien", 
     location: "Ibiza", 
     seadistance: "1 kilometer från stranden", 
     hoteltransfer: "Transfer går att boka", 
     shortdesc: "Hotellet har många faciliteter, bland annat bastu, fitnesscenter och säsongsöppen utomhuspool.",
     talldesc: "Hotellet är skapat i klassisk medelhavsstil och har fritt wi-fi. Hotell erbjuder all inclusive-priser. Dessa priser inkluderar mat och dryck på hotellets fem restauranger. Gäster har tillgång till en dygnsöppen reception, mångspråkig personal och förvaring av bagage. Intill hotellet finns en avgiftsfri parkering. Hos Barracuda hotell finns 128 luftkonditionerade rum, alla sängar har duntäcken och sängtillbehör av högsta kvalitet som utlovar en god nattsömn.",
     image:"https://images.pexels.com/photos/594077/pexels-photo-594077.jpeg",
     features: "1 rumslägenhet • 2 rumslägenhet • Familjerum ",
     payment: "Betala nu • Dela upp betalningen",
     restaurant: "Lactosfri • Vegetarisk • Vegansk",
     price: "Från 21.020:-",
     recomends: "Familjer",
     review: 3.0 ,
     facilities:"✓Bastu  ✓Pool  ✓ WIfI  ✓Fitnesscenter",}
    ]